// auto-generated by yaml_to_cxx.py from test/upstream/regression/3745.yaml
#include "testlib.h"
void test_upstream_regression_3745() {
    enter_section("test_upstream_regression_3745: Test that we do not crash on an error during a function called at unsharding");
    temp_table tbl_table;
    R::Query tbl = tbl_table.table();
    TEST_EQ(tbl.insert(R::array(R::object("id", 0, "a", 5), R::object("id", 1, "a", 6))).run(*conn), (partial(R::Object{{"inserted",2}})));
    TEST_EQ(tbl.reduce([=](R::Var x, R::Var y){ return R::object("a", R::add((*x)["a"], (*y)["a"])); }).run(*conn), (R::Object{{"a",11}}));
    TEST_EQ(tbl.reduce([=](R::Var x, R::Var y){ return R::expr(0)[0]; }).run(*conn), (err("RqlRuntimeError", "Cannot convert NUMBER to SEQUENCE")));
    exit_section();
}
